config/routes.rb
Rails.application.routes.draw do
  resources :users
  resources :outfits #, :except => [:destroy]

  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  get '/logout' => 'sessions#destroy'
  root to: 'welcome#index'
  get '/signup' => 'users#new'
  get '/upload' => 'outfits#new', as: 'upload_outfit'
  post '/upload' => 'outfits#create'
  patch '/upload' => 'outfits#create'
  get '/ootd' => 'search#index', as: 'ootd'
  #delete '/outfits/:id' => 'outfits#destroy', as: 'destroy_outfit'
end

app/models/adapters/twitter_adapter.rb
# module Adapters
#   class TwitterAdapter

#     require 'tweetstream'

#     TweetStream.configure do |config|
#       config.consumer_key       = ENV['TWITTER_KEY']
#       config.consumer_secret    = ENV['TWITTER_SECRET']
#       config.oauth_token        = ENV['OAUTH_TOKEN']
#       config.oauth_token_secret = ENV['OAUTH_TOKEN_SECRET']
#       config.auth_method        = :oauth
#     end

#     def connection
#       @connection = Adapters::TwitterConnection.new
#     end

#   end
# end

app/models/adapters/twitter_client.rb
module Adapters 
  class TwitterClient  < ApplicationController

    def connection
      @connection = TwitterConnection.new(current_user).create_client
    end

    def search(keyword)
    	results = connection.query(q: keyword)
    end


  end
end



# client.search("#ootd").take(10).map {|tweet| auto_link(tweet.text)}

app/models/adapters/twitter_connection.rb
module Adapters
  class TwitterConnection

    attr_reader :client

    def initialize(user)
      @user = user
      @client = create_client
    end

    def create_client
      keys = YAML.load_file('config/application.yml')
      Twitter::REST::Client.new do |config|
        config.consumer_key = keys['CONSUMER_KEY']
        config.consumer_secret = keys['CONSUMER_SECRET']
        config.access_token = keys['ACCESS_TOKEN']
        config.access_token_secret = keys['ACCESS_TOKEN_SECRET']
      end
    end

    def query(search = {})
      results = connection.get("https://api.twitter.com/1.1/search/tweets.json?q=%23ootd&src=typd", {search: search})
      search_results = RecursiveOpenStruct.new(results, :recurse_over_arrays => true)
    end

  end
end

app/models/outfit.rb
class Outfit < ActiveRecord::Base
  belongs_to :user

  validates_presence_of :temp, :name
  validates :rain, inclusion: [true, false]
  has_attached_file :image_upload, styles: { medium: "300x300>", thumb: "100x100>"}
  validates_presence_of :image_upload
  validates_attachment_content_type :image_upload, content_type: /\Aimage\/.*\Z/


  TEMPERATURES = ['super hot', 'hot', 'warm', 'cool', 'cold', 'freezing']


  def self.outfit(current_user, temperature, rain_status, m_or_f)
    if current_user && (Outfit.where(user_id: current_user.id, temp: temperature , rain: rain_status, gender: m_or_f).length > 0)
      Outfit.where(user_id: current_user.id, temp: temperature, rain: rain_status, gender: m_or_f).sample
    else
      Outfit.where(public_setting: true, temp: temperature , rain: rain_status, gender: m_or_f).sample
    end
  end


end

app/models/twitter_connection.rb
require 'pry'
class TwitterConnection

  attr_reader :client

  def initialize(user)
    @user = user
    @client = create_client
  end

  def create_client
    keys = YAML.load_file('config/application.yml')
    Twitter::REST::Client.new do |config|
      config.consumer_key = keys['CONSUMER_KEY']
      config.consumer_secret = keys['CONSUMER_SECRET']
      config.access_token = keys['ACCESS_TOKEN']
      config.access_token_secret = keys['ACCESS_TOKEN_SECRET']
    end
  end

end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :outfits
  has_secure_password

  validates_uniqueness_of :email
  validates_presence_of :name, :email, :gender, :location
  validates_presence_of :password, :on => :create
  validates :location, numericality: {only_integer: true}
  validates_confirmation_of :password
end

app/models/weather.rb
class Weather
  attr_accessor :temp, :rain, :condition, :low_temp

  def initialize(location)

    @weather_at_location = Barometer.new(location).measure

    #Current day temperature    
    @temp = @weather_at_location.today.high.f
    @low_temp = @weather_at_location.today.low.f
    @condition = @weather_at_location.responses.first.forecast.first.icon
  end

  #['super hot', 'hot', 'warm', 'cool', 'cold', 'freezing']

  def temperature
    if @temp.to_i > 90
      "super hot"
    elsif @temp.to_i > 80 
      "hot"
    elsif @temp.to_i > 70
      'warm'
    elsif @temp.to_i > 60
      'cool'
    elsif @temp.to_i > 40
      'cold'
    else
      'freezing'
    end
  end

  #RAIN_KEYWORDS = ['Drizzle', 'Rain', 'Spray', 'Showers', 'Thunderstorm', 'Thunderstorms', 'Squalls']
  RAIN_KEYWORDS = ['chancerain', 'chancetstorms', 'rain', 'tstorms']

  def is_raining?
    rain_check = RAIN_KEYWORDS.any?{|word| word == @condition}
    # rain_check = @condition.split(' ').select do |condition|
    #   RAIN_KEYWORDS.any?{|word| condition}
    # end
    !!rain_check
  end


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  
  include SessionsHelper

end

app/controllers/outfits_controller.rb
class OutfitsController < ApplicationController
  def index
    @outfits = Outfit.where(user_id: current_user.id)
  end

  def new
    @outfit = Outfit.new
  end

  def create
    @outfit = Outfit.create(outfit_params)
    @outfit.image_upload = params[:outfit][:image_upload]
    if @outfit.save
      redirect_to @outfit
    else
      render 'new'
    end
  end

  def edit
    @outfit = Outfit.find(params[:id])
  end

  def update
    @outfit = Outfit.find(params[:id])
    @outfit.update(outfit_params)    
    redirect_to @outfit
    rescue
      flash.now.alert = "Please try again"
      render 'edit'
  end

  def show
    @outfit = Outfit.find(params[:id])
  end

  def destroy
    @outfit = Outfit.find(params[:id])
    @outfit.destroy
    redirect_to outfits_path 
  end

  private

  def outfit_params
       params.require(:outfit).permit(:name, :temp, :rain, :user_id, :gender, :image_upload, :public_setting)
  end
end

app/controllers/search_controller.rb
require 'twitter-text'

class SearchController < ApplicationController

include Twitter::Autolink

  def index
    # TWITTER:
    #get Twitter connection
    @client = TwitterConnection.new(current_user).create_client
    #search for OOTD hashtags and format the first 10
    @tweets = @client.search("#ootd").take(10).map {|tweet| auto_link(tweet.text)}

    #WEATHER:
    #retrieve location from search or from user's stored location
    @location = params[:location] || current_user.location.to_s
    #new weather object based on location
    @weather = Weather.new(@location)

    #WEATHER ATTRIBUTES
    @condition = @weather.is_raining?
    @high_temp = @weather.temp
    @low_temp = @weather.low_temp

    @gender = params[:gender] || current_user.gender
    
    #retrieve proper outfit based on conditions and gender
    @outfit = Outfit.outfit(current_user, @weather.temperature.downcase, @condition, @gender)
  end

    
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
    @user = User.new
  end

  def create
    user = User.find_by_email(params[:email])
    if user && user.authenticate(params[:password])
        log_in(user)
        redirect_to ootd_path
    else
      flash.now.alert = "Sorry, that's an invalid email/password combination!"
      render "new"
    end
  end

  def destroy
    log_out
    redirect_to root_url
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
       log_in(@user)
       redirect_to root_path
     else
       render :new
     end
  end

  private

  def user_params
       params.require(:user).permit(:name, :password, :password_confirmation, :email, :location, :gender)
  end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end


end

app/helpers/application_helper.rb
module ApplicationHelper

end

app/helpers/outfits_helper.rb
module OutfitsHelper
end

app/helpers/search_helper.rb
module SearchHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def log_in(user)
        session[:user_id] = user.id
    end

    def log_out
        session.delete(:user_id)
        @current_user = nil
    end

    def current_user
        @current_user ||= User.find_by(id: session[:user_id])
    end

    def logged_in?
        !current_user.nil?
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/_footer.html.erb
<% if logged_in? %>
  <%= link_to "All Outfits", outfits_path %>
  <%= link_to "Upload an Outfit", new_outfit_path %>
<% end %>

app/views/layouts/_header.html.erb
<% if current_user %>
  Hello, <%= current_user.name %>!
  <%= link_to "Log Out", logout_path %>
<% else %>
  Sign up or log in to add an outfit! <br>
  <%= link_to "Sign Up", signup_path %>
  <%= link_to "Log In", login_path %>
<% end %>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="<%=root_url%>">Rain Or Shine</a>
    </div>

    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <% if current_user %>
       
        <li><a><strong>Welcome, <%= current_user.name %></strong><span class="sr-only">(current)</span></a></li>

         <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">My Account <span class="caret"></span></a>
          <ul class="dropdown-menu" role="menu">
            <li><a href="<%=outfits_path%>">All Outfits</a></li>
            <li><a href="<%=new_outfit_path%>">Upload an Outfit</a></li>
          </ul>
        </li>
      </ul>

      <% else %>
       <li class="active"><a href="<%= signup_path%>">Sign Up <span class="sr-only">(current)</span></a></li>
        <li class="active"><a href="<%= login_path%>">Log In <span class="sr-only">(current)</span></a></li>

        <% end %>

      <!-- <form class="navbar-form navbar-left" role="search">
        <div class="form-group">
          <input type="text" class="form-control" placeholder="Search">
        </div>
        <button type="submit" class="btn btn-default">Submit</button>
      </form> -->

      <% if current_user %>
      <ul class="nav navbar-nav navbar-right">
       <li class="active"><a href="<%= logout_path%>">Log Out <span class="sr-only">(current)</span></a></li>
      </ul>
      <% end %>

    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>WeatherOutfits</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<%= render 'layouts/navbar.html' %><br><br>
<% flash.each do |name, msg| %>
   <%= content_tag :div, msg, :id => "flash_#{name}" %>
 <% end %>
<%= yield %>
</body>
</html>

app/views/outfits/_form.html.erb
<div class="container-fluid">
  <div class="col-md-1"></div>
    <div class="col-md-10">

      <%= form_for @outfit, class: "form-horizontal" do |f| %>
      <!-- error messages: -->
        <% if @outfit.errors.any? %>
          <div id="error_explanation">
            <h2><%= pluralize(@outfit.errors.count, "error") %> prohibited this outfit from being saved:</h2>
            <ul>
            <% @outfit.errors.full_messages.each do |msg| %>
              <li><%= msg %></li>
            <% end %>
            </ul>
          </div>
        <% end %>

        
          <div class="form-group">
            <%= f.label :name %><br>
            <%= f.text_field :name %><br><br>
            <%= f.label :temp, "Temperature" %><br>
            <%= f.collection_select :temp, Outfit::TEMPERATURES, :to_s, :to_s %>
            <br><br>
            <p><strong>Would you wear this outfit if it were raining?</strong></p>
            <%= label :yes, 'Yes' %>
            <%= f.radio_button :rain, true %><br>
            <%= label :no, 'No' %>
            <%= f.radio_button :rain, false %><br>
            <br>
            <p><strong>Is this an outfit for a male or female?</strong></p>
            <%= label :male, 'Male' %>
            <%= f.radio_button :gender, "male" %><br>
            <%= label :female, 'Female' %>
            <%= f.radio_button :gender, "female" %><br><br>
            <p><strong>Would you like this outfit to be visible to others?</strong></p>
            <%= label :yes, 'Yes' %>
            <%= f.radio_button :public_setting, true %><br>
            <%= label :no, 'No' %>
            <%= f.radio_button :public_setting, false %><br><br>
            <p><strong>Please select an image to upload:</strong></p>
            <%= f.file_field :image_upload%>
            <br>
            <%= f.hidden_field :user_id, :value => current_user.id %>
            <div class="actions">
            <%= f.submit 'Upload', class: "btn btn-primary" %>
            </div>
            <br>
            <% end %>

<!--  -->

app/views/outfits/edit.html.erb
<fieldset>
<legend>Edit This Outfit</legend>
<%= render 'form' %>

<%= link_to 'Back to Outfit', @outfit %> 

app/views/outfits/index.html.erb
<!DOCTYPE html>
<html lang="en">
  <div class="container-fluid">
    <div class="col-md-1"></div>
      <div class="col-md-10">
        <% if @outfits.length > 0 %>
          <ul class="row">
          <% @outfits.each do |outfit| %>
            <li class="col-xs-4" align="center"><a href="/outfits/<%=outfit.id%>">
              <br><img src="<%=outfit.image_upload.url(:medium) %>" ><br>
            </a></li>
          <% end %>
          </ul>
        <% else %>
          <p> Oops! You haven't uploaded any outfits yet! </p>
        <% end %>
  		</div>
  	<div class="col-md-4"></div>
  </div>
</html>

app/views/outfits/new.html.erb
<fieldset>
<legend>Upload a New Outfit</legend>
<%= render 'form' %>

app/views/outfits/show.html.erb
<!DOCTYPE html>
<html lang="en">

<div class="container-fluid">

  <div class="col-md-4"></div>

    <div class="col-md-4">
		<div class="panel panel-info">
		  <div class="panel-heading">
		    <h3 class="panel-title" align="center">Outfit Name</h3>
		  </div>
		  <div class="panel-body" align="center">
		    <%= @outfit.name.split.map(&:capitalize).join(' ') %>
		  </div>
		</div>

		<div class="panel panel-default">
		<div class="panel-body" align="center">
		  <%= image_tag @outfit.image_upload.url(:medium)%>
	  	</div>
		</div>

		<div class="panel panel-info">
		  <div class="panel-heading">
		    <h3 class="panel-title" align="center">Outfit Details</h3>
		  </div>
		  <div class="panel-body" align="center">
			<p>This outfit is for <%= @outfit.temp %> weather.</p>
			<% if @outfit.rain == true %>
	  			<p>This is a good outfit for the rain. </p>
			<% end %>
			<% if @outfit.public_setting == true %>
	  			<p><strong>This outfit is visible to others. </strong></p>
			<% end %>

		  </div>
		</div>

		<div align="center">
		<a href="<%=edit_outfit_path%>" class="btn btn-primary" action="<%=edit_outfit_path%>">Edit this outfit</a>
		<a rel="nofollow" data-method="delete" href="/outfits/<%=@outfit.id%>" class="btn btn-danger">Delete this outfit</a>
		</div>

	</div>
  <div class="col-md-4"></div>
</div>
				
</html>

app/views/search/_search_form.html.erb
<!DOCTYPE html>
<html lang="en">

<div class="container-fluid">

	<div class="col-md-4"></div>

		<div class="col-md-4">

			<form class="form-horizontal", action="<%=ootd_path%>", method="get">
			  <fieldset>
			    <legend>Find an Outfit</legend>
			    <div class="form-group">
			      <label for="location" class="col-lg-2 control-label">Location</label>
			      <div class="col-lg-10">
			        <input type="text" class="form-control" id="location" placeholder="Zip Code", name="location" required>
			      </div>
			    </div>
			  
			    <div class="form-group">
			      <label class="col-lg-2 control-label">Select Your Gender</label>
			      <div class="col-lg-10">
			        <div class="radio">
			          <label>
			            <input type="radio" name="gender" id="male" value="male" checked="">
			            Male
			          </label>
			        </div>
			        <div class="radio">
			          <label>
			            <input type="radio" name="gender" id="female" value="female">
			            Female
			          </label>
			        </div>
			      </div>
			    </div>
			  
			    <div class="form-group">
			      <div class="col-lg-10 col-lg-offset-2">
			        <button type="reset" class="btn btn-default">Cancel</button>
			        <button type="submit" class="btn btn-primary">Submit</button>
			      </div>
			    </div>
			  </fieldset>
			</form>

		</div>


	<div class="col-md-4"></div>

</div>


</html>

app/views/search/index.html.erb
<!DOCTYPE html>
<html lang="en">

<div class="container-fluid">

  <div class="col-md-4"></div>

    <div class="col-md-4">

        <div class="panel panel-primary">
          <div class="panel-heading" align="center">

            <% if @location == @location.to_i.to_s %>
              <h3 class="panel-title">Today's weather in <%= @location.to_region(city: true) %></h3>
            <% else %>
              <h3 class="panel-title">Today's weather in <%= @location %></h3>
            <% end %>
          </div>
          <div class="panel-body">

            <table class="table table-striped table-hover ">
            <thead>
            <tr>

            <tr>
            <td align="center"> High of <%= @high_temp %>°F </td>
            <td align="center"> Low of <%= @low_temp %>°F </td>
            </tr>

            </tr>
            </thead>
            <tbody>
            </table>

          </div>
        </div>

            <% if @condition == true %>
              <div class="alert alert-dismissible alert-danger">
                <button type="button" class="close" data-dismiss="alert">close</button>
                <strong>Bring an umbrella!</strong> Rain is in the forecast
              </div>
            <% end %>

            <% if @condition == true && @condition == "squall" %>
              <div class="alert alert-dismissible alert-warning">
                <button type="button" class="close" data-dismiss="alert">&close;</button>
                <h4>Warning!</h4>
                <p>Watch out for sudden squalls!</p>
              </div>
            <% end %>

          <div class="panel panel-default">
          <div class="panel-body" align="center">
            <%= image_tag @outfit.image_upload.url(:medium)%>
          </div>
          </div>

          <div class="well well-sm" align="center">
          <a href="#bottom" id="hulk">View The Top #ootd Tweets!</a>
          </div>

          <div class="well well-sm" align="center">
          Not your location? Search Again
          </div>


    </div>
  <div class="col-md-4"></div>
</div>

<%= render 'search_form' %>

        

<A NAME="bottom">
<div class="panel panel-default">
  <div class="panel-body">
    <ul>
      <% @tweets.each do |tweet| %>
        <p align="center"><%= tweet.html_safe %></p>
      <% end %>
    </ul>
  </div>
</div>
</a>


</html>

app/views/users/_form.html.erb
<div class="container-fluid">
  <div class="col-md-2"></div>
    <div class="col-md-8">
      <%= form_for @user do |f| %>
        <div class="form-group" id="new_resource_body">
          <%= f.label :name %>
          <%= f.text_field :name, class: "form-control" %>
          <%= f.label :email %>
          <%= f.text_field :email, class: "form-control" %>
          <%= f.label :location %>
          <%= f.text_field :location, class: "form-control" %>
          <p>Gender</p>
          <%= label :male, 'Male' %>
          <%= f.radio_button :gender, 'male' %><br>
          <%= label :female, 'Female' %>
          <%= f.radio_button :gender, 'female' %><br>
          <%= f.label :password %>
          <%= f.password_field :password, class: "form-control" %>
          <%= f.label :password_confirmation %>
          <%= f.password_field :password_confirmation, class: "form-control" %>
          <br>

        <%= f.submit class: "btn btn-primary" %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/users/new.html.erb
<%= render 'form' %>

app/views/users/show.html.erb
<p>
  Hi, <%= current_user.name %>!
</p>

<p>
  Daily Outfit Goes Here
</p>

app/views/welcome/index.html.erb
<%= render 'search/search_form' %>